config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  resources :proveedors
  resources :units
  resources :categories
  resources :brands
 
get '/brands_suggestion', to: 'brands_suggestion#index'
get '/validate_suggested_brand', to: 'validate_suggested_brand#index'

  root 'pages#index'
  get 'pages/index'
  get 'profile', to: 'pages#show'
  get '/secret', to: 'pages#index', as: :secret
  
 
resources :users, only: [:new, :create]
get '/sign_up', to: 'users#new', as: :sign_up




resources :sessions, only: [:new, :create, :destroy]
get 'sessions/new'
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get '/log_in', to: 'sessions#new', as: :log_in
delete '/log_out', to: 'sessions#destroy', as: :log_out
delete 'logout', to: 'sessions#destroy'
end

app/models/brand.rb
class Brand < ActiveRecord::Base


	validates :nombre, presence: true


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
PAGE_SIZE = 5

def index
 @page = (params[:page] || 0).to_i
 @keywords = params[:keywords]

 search = Search.new(@page, PAGE_SIZE, @keywords)
 @brands, @number_of_pages = search.brands_by_nombre
end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:nombre, :descripcion)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="panel-body">
      <%= form_for(brand) do |f| %>
        <% if brand.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

            <ul>
            <% brand.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :nombre, autofocus: true, placeholder: "Nombre", class: "form-control" %>
        </div>

     </div>
        <div class="form-group">
          <%= f.text_area :descripcion, autofocus: true, placeholder: "Descripción", class: "form-control"%>
        </div>
        
        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/brands/_pager.html.erb
<nav>
 <ul class="pager">
  <li class="previous <%= page == 0 ? 'disabled' : '' %>">
   <%= link_to_if page > 0, "&larr; Anterior".html_safe,
                  brands_path(keywords: keywords, page: page - 1) %>
  </li>
  <li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
   <%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
                  brands_path(keywords: keywords, page: page + 1) %>
  </li>
 </ul>
</nav>

app/views/brands/_results_search.html.erb
<table class="table">
 <thead>
  <tr>
   <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
  </tr>
  <tr>
   <th>Nombre</th>
   <th>Fecha de Alta</th>
   <th>Fecha de Modificación</th>
   <th colspan="2"></th>
  </tr>
 </thead>

 <tbody>
  <div id="brands">
   <% @brands.each do |brand| %>
    <tr>
     <td><%= brand.nombre %></td>
     <td><%= brand.created_at.strftime("%d/%m/%Y") %></td>
     <td><%= brand.updated_at.strftime("%d/%m/%Y") %></td>
     <td>
      <%= button_to brand_path(brand), {method: :get, class: "btn btn-info"} do %>
       <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Mostrar
      <% end %>
     </td>
     <td>
         <td>
          <%= button_to edit_brand_path(brand), {method: :get, class: "btn btn-warning"} do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
          <% end %>
      </td> 

     <td>
      <%= button_to brand, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
       <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
      <% end %>
     </td>
    </tr>
   <% end %>
  </div>
 </tbody>
</table>

app/views/brands/edit.html.erb
<div class="container-fluid">
 <div class="row">
  <h1>Editar Marca</h1>

  <%= render 'form', brand: @brand %>

  <%= link_to 'Volver', brands_path %>

 </div>
</div>

app/views/brands/index.html.erb
<div class="panel panel-default">
 <div class="panel-heading">Marcas</div>
 <div class="panel-body">
  <%= render partial: 'layouts/search_form', locals: { search_entity: 'brands', word: "Marca" } %>
  <br>
  <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
   <p>
    <%= button_to new_brand_path, {method: :get, class: "btn btn-success"} do %>
     <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nueva Marca
    <% end %>
   </p>
  </div>
 </div>
 <%= render partial: 'results_search' %>
</div>

app/views/brands/new.html.erb
<div class="container-fluid">
 <div class="row">
  <h1>Nueva Marca</h1>

  <%= render 'form', brand: @brand %>

  <%= link_to 'Volver', brands_path %>
 </div>
</div>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @brand.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @brand.descripcion %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>