config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  resources :proveedors
  resources :units
  resources :categories
  resources :brands
 
get '/brands_suggestion', to: 'brands_suggestion#index'
get '/validate_suggested_brand', to: 'validate_suggested_brand#index'

  root 'pages#index'
  get 'pages/index'
  get 'profile', to: 'pages#show'
  get '/secret', to: 'pages#index', as: :secret
  
 
resources :users, only: [:new, :create]
get '/sign_up', to: 'users#new', as: :sign_up




resources :sessions, only: [:new, :create, :destroy]
get 'sessions/new'
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get '/log_in', to: 'sessions#new', as: :log_in
delete '/log_out', to: 'sessions#destroy', as: :log_out
delete 'logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category  < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  PAGE_SIZE = 10

  # GET /categories
  # GET /categories.json
  def index
    @page = (params[:page] || 0).to_i
    @keywords = params[:keywords]

    search = Search.new(@page, PAGE_SIZE, @keywords)
    @categories, @number_of_pages = search.categories_by_nombre
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Categoría creada.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Categoría modficada.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:nombre,:descripcion)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="panel-body">
      <%= form_for(category) do |f| %>
        <% if category.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

            <ul>
            <% category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.text_field :nombre, autofocus: true, placeholder: "Nombre", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.text_area :descripcion, autofocus: true, placeholder: "Descripción", class: "form-control"%>
        </div>

        <%= f.submit "Aceptar", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_pager.html.erb
<nav>
	<ul class="pager">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Anterior".html_safe,
						categories_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						categories_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/categories/_results_search.html.erb
<table class="table">
  <thead>
    <tr>
      <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
    </tr>
    <tr>
      <th>Nombre</th>
      <th>Fecha de Alta</th>
      <th>Fecha de Modificación</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.nombre %></td>
        <td><%= category.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= category.updated_at.strftime("%d/%m/%Y") %></td>
        <td>
     <td>
      <%= button_to category_path(category), {method: :get, class: "btn btn-info"} do %>
       <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Mostrar
      <% end %>
     </td>
     <td>
          <%= button_to edit_category_path(category), {method: :get, class: "btn btn-warning"} do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
          <% end %>
      </td> 

        <td>
          <%= button_to category, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Editar Categoría</h1>

		<%= render 'form', category: @category %>

		<%= link_to 'Volver', categories_path %>

	</div>
</div>

app/views/categories/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Categorías</div>
  <div class="panel-body">
    <%= render partial: 'layouts/search_form', locals: { search_entity: 'categories', word: "Categoría" } %>
    <br>
    <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
      <p>
        <%= button_to new_category_path, {method: :get, class: "btn btn-success"} do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nueva Categoría
        <% end %>
      </p>
    </div>
  </div>
  <%= render partial: 'results_search' %>
</div>

app/views/categories/new.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Nueva Categoría</h1>

		<%= render 'form', category: @category %>

		<%= link_to 'Volver', categories_path %>
	</div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.nombre %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>