config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  resources :proveedors
  resources :units
  resources :categories
  resources :brands
 
get '/brands_suggestion', to: 'brands_suggestion#index'
get '/validate_suggested_brand', to: 'validate_suggested_brand#index'

  root 'pages#index'
  get 'pages/index'
  get 'profile', to: 'pages#show'
  get '/secret', to: 'pages#index', as: :secret
  
 
resources :users, only: [:new, :create]
get '/sign_up', to: 'users#new', as: :sign_up




resources :sessions, only: [:new, :create, :destroy]
get 'sessions/new'
get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
get '/log_in', to: 'sessions#new', as: :log_in
delete '/log_out', to: 'sessions#destroy', as: :log_out
delete 'logout', to: 'sessions#destroy'
end

app/models/brand.rb
class Brand < ActiveRecord::Base


	validates :nombre, presence: true


end

app/models/category.rb
class Category  < ActiveRecord::Base
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
	 belongs_to :provincia
	 has_many :proveedor

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :proveedor
  belongs_to :brand
  belongs_to :unit
  belongs_to :category

 validates :descripcion, presence: true

 def item_descripcion
  self.descripcion + ( (self.brand != nil) ? ' ' + self.brand.nombre : '' )
 end

 def brand_nombre
  if self.brand
   self.brand.nombre
  else
   ''
  end
 end
end

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  belongs_to :comuna
end

app/models/provincia.rb
class Provincia < ActiveRecord::Base
		  self.table_name = "provincias"
		    belongs_to :region
		    has_many :comuna
end

app/models/region.rb
class Region < ActiveRecord::Base
	 self.table_name = "regiones"
	 has_many :provincia

end

app/models/search.rb
class Search
 def initialize(page, page_size, keywords)
  @page = page
  @page_size = page_size
  @offset = page_size * page
  @keywords = keywords
 end


 def brands_by_nombre
  if @keywords.present?
   brands = Brand.where(nombre_condition).order(:nombre).offset(@offset).limit(@page_size)
   @number_of_records = Brand.where(nombre_condition).count
  else
   brands = Brand.order(:nombre).offset(@offset).limit(@page_size)
   @number_of_records = Brand.count
  end
 
  return brands, number_of_pages
 end

def categories_by_nombre
    if @keywords.present?
        categories = Category.where(nombre_condition).order(:nombre).offset(@offset).limit(@page_size)
        @number_of_records = Category.where(nombre_condition).count
      else
        categories = Category.order(:nombre).offset(@offset).limit(@page_size)
        @number_of_records = Category.count
      end
      
      return categories, number_of_pages
end

 def units_by_nombre
   if @keywords.present?
     units = Unit.where(nombre_condition).order(:nombre).offset(@offset).limit(@page_size)
     @number_of_records = Unit.where(nombre_condition).count
   else
     units = Unit.order(:nombre).offset(@offset).limit(@page_size)
     @number_of_records = Unit.count
   end
 
   return units, number_of_pages
 end

  def items_by_descripcion
    if @keywords.present?
        items = Item.where(descripcion_condition).order(:descripcion).offset(@offset).limit(@page_size)
        @number_of_records = Item.where(descripcion_condition).count
      else
        items = Item.order(:descripcion).offset(@offset).limit(@page_size)
        @number_of_records = Item.count
      end
      
      return items, number_of_pages
  end

 private

 def nombre_condition
  nombre_condition = "unaccent(lower(nombre)) LIKE '%#{I18n.transliterate(@keywords.downcase)}%'"
 end

 def number_of_pages
  number_of_pages = (@number_of_records % @page_size) == 0 ? 
  @number_of_records / @page_size - 1 : @number_of_records / @page_size
 end

  def descripcion_condition
    descripcion_condition = "unaccent(lower(descripcion)) LIKE '%#{I18n.transliterate(@keywords.downcase)}%'"
end

end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

	belongs_to :comuna

 validates :password, length: { minimum: 3 }
validates :password, confirmation: true
validates :email, uniqueness: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<div class="container-fluid">
 <div class="row">
  <% if notice.present? %>
   <div class="alert alert-info" role="alert"><%= notice %></div>
  <% end %>

  <% if alert.present? %>
   <div class="alert alert-danger" role="alert"><%= alert %></div>
  <% end %>
 </div>
</div>

app/views/layouts/_search_form.html.erb
<section class="search-form">
 <%= form_for search_entity, method: :get do |f| %>
  <div class="input-group">
   <%= label_tag :keywords, nil, class: "sr-only" %>
   <%= text_field_tag :keywords, nil, placeholder: "Buscar",
                       class: "form-control", value: "#{@keywords}" %>
   <span class="input-group-btn">
    <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
     <span class="glyphicon glyphicon-search"></span> Buscar <%= "#{word}" %>
    <% end %>
   </span>
  </div>
 <% end %>
</section>

app/views/layouts/_sidebar.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
 <div class="container-fluid">
  <div class="navbar-header">
   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
   <span class="sr-only">Toggle navigation</span>
   <span class="icon-bar"></span>
   <span class="icon-bar"></span>
   <span class="icon-bar"></span>
  </button> 
 </div>
 <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
  <ul class="nav navbar-nav">
   <li class="<%= current_page?(root_path) ? "active" : "" %>">
    <a href="<%= root_path %>">
     Inicio
     <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-blackboard"></span>
    </a>
   </li> 
 
   <li >
    <a href="#">
     Ventas
     <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-shopping-cart"></span>
    </a>
   </li> 
 
   <li >
    <a href="#">
     Contabilidad
     <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></span>
    </a>
   </li>

   <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Almacén <span class="caret"></span>
     <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span>
    </a>
          <ul class="dropdown-menu forAnimate" role="menu">
            <li class="<%= current_page?(items_path) ? "active" : "" %>"><%= link_to 'Artículos', items_path %></li>
</ul>
   </li>

   <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
     Configuración
     <span class="caret"></span>
     <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-wrench"></span>
    </a>
    <ul class="dropdown-menu forAnimate" role="menu">

     <li class="<%= current_page?(brands_path) ? "active" : "" %>"><%= link_to 'Marcas', brands_path %></li>
     <li class="<%= current_page?(categories_path) ? "active" : "" %>"><%= link_to 'Categorías', categories_path %></li>
     <li class="<%= current_page?(units_path) ? "active" : "" %>"><%= link_to 'Unidades', units_path %></li>
     
     <li class="divider"></li>
     <li><a href="#">Respaldo</a></li>
    </ul>
   </li>
  </ul>
 </div>
 </div>
</nav>

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="container-fluid">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="#"><%= Rails.application.class.parent_name %></a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
     <ul class="nav navbar-nav navbar-right">
     <% if current_user %>
            
          <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'sign up', sign_up_path%></li>
      
          <% end %>
       <li><a href="#">Ayuda</a></li>
       <li><a href="#">Configuración</a></li>

       <% if current_user %>
        <ul class="nav navbar-nav pull-right">
           <li><span><%= current_user.nombre %></span></li>
           <li><%= link_to 'Log Out', log_out_path, method: :delete %></li>
       </ul>
       <% end %>
     </ul>
   <form class="navbar-form navbar-right">
     <input type="text" class="form-control" placeholder="Buscar...">
   </form>
  </div>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shop</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>

 <body>
  <%= render 'layouts/topbar' %>

  <% if current_user %>
   <div class="container-fluid">
    <div class="row">
     <%= render 'layouts/sidebar' %>

     <div class="main">
      <%= render 'layouts/alerts' %>
 
      <%= yield %>
     </div>
    </div>
   </div>
  <% else %>
   <br>
   <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
     <%= render 'layouts/alerts' %>
    </div>
   </div>
 

   <%= yield %>
  <% end %>

 </body>
 
</html>

app/views/pages/index.html.erb
<h1>Welcome!</h1>

<p>Restricted area for authorized users only.</p>

app/views/pages/show.html.erb
<div class="row">
	<div class="col-md-6 col md-offset-3">
		<h1>Profile</h1>

		<% user = current_user %>

		<table class="table">
			<tr>
				<th>Name</th>
				<td><%= user.nombre %></td>
			</tr>
			<tr>
				<th>Email</th>
				<td><%= user.email %></td>
			</tr>
 			<tr>
				<th>Direccion</th>
				<td><%= user.calle %></td>
			</tr>
			 <tr>
				<th>Telefono</th>
				<td><%= user.telefono %></td>
			</tr>
			<tr>
				<th>Comuna</th>
				<td><%= user.comuna.nombre %></td>
			</tr>
			<tr>
				<th>Fecha de ingreso</th>
				<td><%= user.fechaingreso %></td>
			</tr>
			 <tr>
				<th>Sueldo</th>
				<td><%= user.sueldo %></td>
			</tr>
			<tr>
				<th>Rut</th>
				<td><%= user.rut %></td>
			</tr>
		</table>
	</div>
</div>

app/views/shared/_current_users.html.erb
<div class="col-sm-3 well well-sm">
  <h3>Currently active users:</h3>
  <ul>
    <% current_users.each do |user| %>
      <li><%= user.nombre %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>